<?php

namespace Database\Factories;

use App\Enums\TicketStatus;
use App\Models\Ticket;
use Illuminate\Database\Eloquent\Factories\Factory;

class TicketFactory extends Factory
{
    protected $model = Ticket::class;

    public function definition(): array
    {
        return [
            // ticket_uid is auto-generated by the Ticket model's creating() hook.
            'name' => $this->faker->name(),
            'email' => $this->faker->safeEmail(),
            'phone' => $this->faker->numerify('01#########'),
            'price' => $this->faker->randomFloat(2, 100, 5000),
            'message' => $this->faker->paragraph(),
            'status' => $this->faker->randomElement(TicketStatus::cases())->value,
        ];
    }
}
